<?php


namespace Hallekamp\NoMagicProperties;


use Illuminate\Support\ServiceProvider;

class PackageServiceProvider extends ServiceProvider
{

    protected $defer = false;

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(){

    }
}
